#!/usr/bin/env python
import argparse
import logging
from common import wabisabi_status_checker

parser = argparse.ArgumentParser()

parser.add_argument(
    metavar="output_filename",
    dest="output_filename",
    help="The path to the output file.",
)

args = parser.parse_args()

logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s %(levelname)s %(message)s")
wabisabi_status_checker(args.output_filename)
